### ISSUE TITLE
Crash when user changes name

### ISSUE THREAD

**Issue by johenrik** [enonic/app-azure-ad-idprovider#3] opened 2021-10-06 14:31 UTC
A user changed name in AD (she got married) and then she was unable to log in anymore. No email or ID was changed, only the last name of the user. It seems like the name of a user is used as a unique key, but I don't think this how it should be. Ideally we should get some proper ID from AzureAD, but not sure what is being sent back. At least I think a user should be able to change names and still log in as long as the email is the same. I have attached the exception that crashes (user anonymised).

[exception.txt](https://github.com/GravitonDigital/app-azure-ad-idprovider/files/7294820/exception.txt)

**Comment by danhul** [comment] 2021-11-12 10:21
This problem is caused by the fact that the IdProvider is setup to use username as unique ID mapping to Enonic. One should rather have used ${objectSid} as default. This is how the ADFS IdProvider works. It will be nice if you could release a new major version that changes the default vale to ${objectSid}. Existing users could then simply update the IdProvider configuration to use ${name} for backward compatiblity.

**Comment by espen42** [comment] 2023-03-27 11:49
This is addressed by version 2.0.1 - notes: https://discuss.enonic.com/t/azure-id-provider-bugfix-update-2-0-1/2975

**Closed** 2023-04-12 08:28 UTC
